#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7C4504A4D75CF3DC (oheger@apache.org)
#
Name     : jdk-commons-beanutils
Version  : 1.9.2
Release  : 3
URL      : http://archive.apache.org/dist/commons/beanutils/source/commons-beanutils-1.9.2-src.tar.gz
Source0  : http://archive.apache.org/dist/commons/beanutils/source/commons-beanutils-1.9.2-src.tar.gz
Source99 : http://archive.apache.org/dist/commons/beanutils/source/commons-beanutils-1.9.2-src.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: jdk-commons-beanutils-data
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-apache-parent
BuildRequires : jdk-aqute-bndlib
BuildRequires : jdk-atinject
BuildRequires : jdk-bsh
BuildRequires : jdk-build-helper-maven-plugin
BuildRequires : jdk-buildnumber-maven-plugin
BuildRequires : jdk-cdi-api
BuildRequires : jdk-cglib
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-digester
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-commons-parent
BuildRequires : jdk-commons-validator
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-easymock3
BuildRequires : jdk-eclipse-eclipse
BuildRequires : jdk-eclipse-osgi
BuildRequires : jdk-eclipse-osgi-services
BuildRequires : jdk-enforcer
BuildRequires : jdk-felix
BuildRequires : jdk-felix-bundlerepository
BuildRequires : jdk-felix-framework
BuildRequires : jdk-felix-osgi-foundation
BuildRequires : jdk-felix-utils
BuildRequires : jdk-glassfish-servlet-api
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-jna
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-kxml
BuildRequires : jdk-log4j
BuildRequires : jdk-maven-antrun-plugin
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-artifact-resolver
BuildRequires : jdk-maven-bundle-plugin
BuildRequires : jdk-maven-common-artifact-filters
BuildRequires : jdk-maven-compiler-plugin
BuildRequires : jdk-maven-dependency-tree
BuildRequires : jdk-maven-filtering
BuildRequires : jdk-maven-invoker
BuildRequires : jdk-maven-jar-plugin
BuildRequires : jdk-maven-javadoc-plugin
BuildRequires : jdk-maven-plugin-testing
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-remote-resources-plugin
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-reporting-impl
BuildRequires : jdk-maven-resources-plugin
BuildRequires : jdk-maven-scm
BuildRequires : jdk-maven-shared-incremental
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-objenesis
BuildRequires : jdk-osgi-compendium
BuildRequires : jdk-osgi-core
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-compiler
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interactivity
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-resources
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-sisu
BuildRequires : jdk-slf4j
BuildRequires : jdk-snappy
BuildRequires : jdk-surefire
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : jdk-xz
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn

%description
No detailed description available

%package data
Summary: data components for the jdk-commons-beanutils package.
Group: Data

%description data
data components for the jdk-commons-beanutils package.


%prep
%setup -q -n commons-beanutils-1.9.2-src

python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :maven-assembly-plugin
python3 /usr/share/java-utils/mvn_alias.py :{*} :@1-core :@1-bean-collections
python3 /usr/share/java-utils/mvn_alias.py :{*} org.apache.commons:@1 org.apache.commons:@1-core org.apache.commons:@1-bean-collections
python3 /usr/share/java-utils/mvn_file.py : apache-commons-beanutils apache-commons-beanutils-core apache-commons-beanutils-bean-collections
python3 /usr/share/java-utils/mvn_file.py : commons-beanutils commons-beanutils-core commons-beanutils-bean-collections

%build
python3 /usr/share/java-utils/mvn_build.py -f

%install
xmvn-install  -R .xmvn-reactor -n commons-beanutils-1.9.2-src -d %{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/apache-commons-beanutils-bean-collections.jar
/usr/share/java/apache-commons-beanutils-core.jar
/usr/share/java/apache-commons-beanutils.jar
/usr/share/java/commons-beanutils-bean-collections.jar
/usr/share/java/commons-beanutils-core.jar
/usr/share/java/commons-beanutils.jar
/usr/share/maven-metadata/commons-beanutils-1.9.2-src.xml
/usr/share/maven-poms/apache-commons-beanutils-bean-collections.pom
/usr/share/maven-poms/apache-commons-beanutils-core.pom
/usr/share/maven-poms/apache-commons-beanutils.pom
/usr/share/maven-poms/commons-beanutils-bean-collections.pom
/usr/share/maven-poms/commons-beanutils-core.pom
/usr/share/maven-poms/commons-beanutils.pom
